//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.MyEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTemp
    {
        public long ID { get; set; }
        public string UniqueUserID { get; set; }
        public string FullName { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string Email { get; set; }
        public string GoogleToken { get; set; }
    }
}
